const $=(q,s=document)=>s.querySelector(q), $$=(q,s=document)=>[...s.querySelectorAll(q)];
setTimeout(()=>$('#boot').classList.add('done'),950);

let topZ=20;
$$('.window').forEach(win=>{
  win.addEventListener('pointerdown',()=>{$$('.window').forEach(w=>w.classList.remove('focused'));win.classList.add('focused');win.style.zIndex=++topZ});
  $('header button',win).addEventListener('click',e=>{e.stopPropagation();win.classList.add('closed')});
  const bar=$('header',win);let moving=false,dx=0,dy=0;
  bar.addEventListener('pointerdown',e=>{if(innerWidth<900)return;moving=true;dx=e.clientX-win.offsetLeft;dy=e.clientY-win.offsetTop;bar.setPointerCapture(e.pointerId)});
  bar.addEventListener('pointermove',e=>{if(!moving)return;win.style.left=Math.max(0,Math.min(innerWidth-win.offsetWidth,e.clientX-dx))+'px';win.style.top=Math.max(0,Math.min(innerHeight-win.offsetHeight,e.clientY-dy))+'px'});
  bar.addEventListener('pointerup',()=>moving=false);
});
$$('[data-restore]').forEach(b=>b.addEventListener('click',()=>{const w=$(`[data-window="${b.dataset.restore}"]`);w.classList.remove('closed');w.style.zIndex=++topZ}));
$('#fullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());

const pad=n=>String(n).padStart(2,'0');
function clocks(){const d=new Date();$('#hour').textContent=pad(d.getHours());$('#minute').textContent=pad(d.getMinutes());$('#second').textContent=pad(d.getSeconds());$('#day').textContent=d.getDate();$('#month').textContent=d.toLocaleString('en',{month:'long'});$('#bog').textContent=`${pad((d.getHours()+21)%24)}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;$('#mat').textContent=`${pad((d.getHours()+1)%24)}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;const t=Math.max(0,new Date(d.getFullYear(),d.getMonth(),d.getDate()+9)-d),s=Math.floor(t/1000);$('#countdown').textContent=`01w 02d ${pad(Math.floor(s/3600)%24)}h ${pad(Math.floor(s/60)%60)}m ${pad(s%60)}s`}
setInterval(clocks,1000);clocks();
const now=new Date(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();$('#dates').textContent=Array.from({length:days},(_,i)=>pad(i+1)).join(' ');

$('#numbers').innerHTML=Array.from({length:30},()=>`<span>${Math.floor(10000000+Math.random()*89999999)}</span>`).join('');
$('#bars').innerHTML=Array.from({length:11},(_,i)=>`<i style="height:${18+i*7}%"></i>`).join('');
const services=['Event Log','Event System','Network Location Awareness','DHCP Client','Local Client','ENS Client','Network Connection Broker'];
$('#logs').innerHTML=services.map(x=>`<div>${x}</div>`).join('');
function process(){const d=new Date();$('#process').textContent=Array.from({length:6},(_,i)=>`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad((d.getSeconds()-i+60)%60)}   ${102100+i*17}   ${['explorer','Application Frame Host','Service Host: Local Broker','Runtime Broker'][i%4]}`).join('\n')}setInterval(process,1000);process();

const spec=$('#spectrum'),sctx=spec.getContext('2d'),net=$('#network'),nctx=net.getContext('2d');let phase=0;
function draw(){phase+=.055;spec.width=spec.clientWidth*devicePixelRatio;spec.height=spec.clientHeight*devicePixelRatio;sctx.scale(devicePixelRatio,devicePixelRatio);sctx.clearRect(0,0,spec.clientWidth,spec.clientHeight);const count=64,w=spec.clientWidth/count;for(let i=0;i<count;i++){const h=(.12+Math.abs(Math.sin(i*.33+phase))*Math.random()*.78)*spec.clientHeight;sctx.fillStyle=i%7===0?'#91f6ff':'#23b9f4';sctx.fillRect(i*w,spec.clientHeight-h,w*.55,h)}net.width=net.clientWidth*devicePixelRatio;net.height=net.clientHeight*devicePixelRatio;nctx.scale(devicePixelRatio,devicePixelRatio);nctx.strokeStyle='#179eff';nctx.lineWidth=1;nctx.beginPath();for(let x=0;x<net.clientWidth;x++){const spike=Math.max(0,Math.sin(x*.06+phase*2))**18;const y=net.clientHeight*.85-spike*net.clientHeight*.65-Math.random()*4;x?nctx.lineTo(x,y):nctx.moveTo(x,y)}nctx.stroke();requestAnimationFrame(draw)}draw();

// Visual page editor ---------------------------------------------------------
const editor=$('#editor'), editButton=$('#edit-toggle'), zoom=$('#window-zoom');let selectedWindow=null,customIndex=0;
function selectWindow(win){if(!$('#desktop').classList.contains('edit-mode'))return;$$('.window').forEach(w=>w.classList.remove('selected'));selectedWindow=win;win.classList.add('selected');$('#selected-name').textContent=$('header span',win)?.textContent||'窗口';const z=Number(win.dataset.zoom||100);zoom.value=z;$('#zoom-output').textContent=z+'%'}
$('#desktop').addEventListener('pointerdown',e=>{const win=e.target.closest('.window');if(win)selectWindow(win)});
function toggleEditor(force){const on=force??!$('#desktop').classList.contains('edit-mode');$('#desktop').classList.toggle('edit-mode',on);editor.classList.toggle('open',on);editButton.classList.toggle('active',on);if(!on){$$('[contenteditable]').forEach(x=>x.contentEditable='false');$$('.window').forEach(w=>w.classList.remove('selected'));selectedWindow=null}}
editButton.addEventListener('click',()=>toggleEditor());$('#editor-close').addEventListener('click',()=>toggleEditor(false));
zoom.addEventListener('input',()=>{if(!selectedWindow)return;const z=Number(zoom.value);selectedWindow.dataset.zoom=z;selectedWindow.classList.add('zooming');selectedWindow.style.transform=`scale(${z/100})`;$('#zoom-output').textContent=z+'%'});
function editorDrag(win){const bar=$('header',win);let moving=false,dx=0,dy=0;bar.addEventListener('pointerdown',e=>{if(!$('#desktop').classList.contains('edit-mode')||e.target.closest('button'))return;moving=true;dx=e.clientX-win.offsetLeft;dy=e.clientY-win.offsetTop;bar.setPointerCapture(e.pointerId)});bar.addEventListener('pointermove',e=>{if(!moving)return;win.style.left=Math.max(0,e.clientX-dx)+'px';win.style.top=Math.max(0,e.clientY-dy)+'px'});bar.addEventListener('pointerup',()=>moving=false);$('header button',win).addEventListener('click',()=>win.classList.add('closed'))}
function createWindow(type,data={}){const win=document.createElement('section');const id=data.id||`custom-${Date.now()}-${customIndex++}`;win.className=`window custom-window ${type==='image'?'image-window':''}`;win.dataset.custom=id;win.style.cssText=data.css||`left:${120+customIndex*24}px;top:${90+customIndex*20}px;width:330px;height:230px;z-index:${++topZ}`;win.innerHTML=`<header><span>${data.title||(type==='image'?'新图片':'新文字')}</span><button aria-label="close">×</button></header><div class="editable-body">${data.body||'点击“编辑文字内容”后修改这里。'}</div>`;if(data.background)$('.editable-body',win).style.backgroundImage=data.background;$('#desktop').insertBefore(win,$('#dock'));editorDrag(win);selectWindow(win);return win}
$('#add-text').addEventListener('click',()=>createWindow('text'));$('#add-image').addEventListener('click',()=>{const w=createWindow('image',{body:''});selectedWindow=w;$('#image-picker').click()});
$('#duplicate-window').addEventListener('click',()=>{if(!selectedWindow)return alert('请先选择一个窗口');if(selectedWindow.dataset.custom){const b=$('.editable-body',selectedWindow);createWindow(selectedWindow.classList.contains('image-window')?'image':'text',{title:$('header span',selectedWindow).textContent,body:b.innerHTML,background:b.style.backgroundImage})}else{const copy=selectedWindow.cloneNode(true);copy.dataset.custom=`custom-${Date.now()}`;copy.classList.add('custom-window');copy.style.left=selectedWindow.offsetLeft+28+'px';copy.style.top=selectedWindow.offsetTop+28+'px';copy.querySelectorAll('canvas').forEach(c=>c.remove());$('#desktop').insertBefore(copy,$('#dock'));editorDrag(copy);selectWindow(copy)}});
$('#delete-window').addEventListener('click',()=>{if(!selectedWindow)return alert('请先选择一个窗口');selectedWindow.classList.add('editor-deleted');selectedWindow.classList.remove('selected');selectedWindow=null;$('#selected-name').textContent='未选择窗口'});
$('#edit-content').addEventListener('click',()=>{if(!selectedWindow)return alert('请先选择一个窗口');const nodes=$$('header span,.editable-body,.counter span,.counter strong,.track b,.track span,.service div,.number-grid span',selectedWindow);nodes.forEach(n=>n.contentEditable=n.contentEditable==='true'?'false':'true');nodes[0]?.focus()});
$('#replace-image').addEventListener('click',()=>{if(!selectedWindow)return alert('请先选择一个窗口');$('#image-picker').click()});
$('#image-picker').addEventListener('change',e=>{const file=e.target.files[0];if(!file||!selectedWindow)return;const target=$('.editable-body,.crt-image,.avatar-image,.eye-image,.album',selectedWindow);if(!target)return alert('该窗口没有可替换的图片区域');const reader=new FileReader();reader.onload=()=>{target.style.backgroundImage=`url('${reader.result}')`;target.dataset.userImage=reader.result};reader.readAsDataURL(file);e.target.value=''});
function snapshot(){return $$('.window').map(w=>({key:w.dataset.window||w.dataset.custom,custom:w.dataset.custom||null,type:w.classList.contains('image-window')?'image':'text',title:$('header span',w)?.textContent||'',body:w.dataset.custom?$('.editable-body',w)?.innerHTML:'',background:w.dataset.custom?$('.editable-body',w)?.style.backgroundImage:'',css:`left:${w.offsetLeft}px;top:${w.offsetTop}px;width:${w.offsetWidth}px;height:${w.offsetHeight}px;z-index:${w.style.zIndex||3};transform:${w.style.transform||'none'}`,zoom:w.dataset.zoom||100,deleted:w.classList.contains('editor-deleted'),image:$('.crt-image,.avatar-image,.eye-image,.album',w)?.dataset.userImage||''}))}
function saveLayout(){try{localStorage.setItem('sunny-desktop-layout',JSON.stringify(snapshot()));$('#selected-name').textContent='布局已保存'}catch{alert('图片文件过大，布局尺寸和文字可保存，但自定义图片无法存入浏览器。')}}$('#save-layout').addEventListener('click',saveLayout);
function restoreLayout(){let data;try{data=JSON.parse(localStorage.getItem('sunny-desktop-layout')||'null')}catch{}if(!data)return;data.filter(x=>x.custom).forEach(x=>createWindow(x.type,x));data.filter(x=>!x.custom).forEach(x=>{const w=$(`[data-window="${x.key}"]`);if(!w)return;w.style.cssText=x.css;w.dataset.zoom=x.zoom;if(x.deleted)w.classList.add('editor-deleted');const title=$('header span',w);if(title)title.textContent=x.title;if(x.image){const target=$('.crt-image,.avatar-image,.eye-image,.album',w);if(target){target.style.backgroundImage=`url('${x.image}')`;target.dataset.userImage=x.image}}})}restoreLayout();
$('#reset-layout').addEventListener('click',()=>{localStorage.removeItem('sunny-desktop-layout');location.reload()});
